### ISSUE TITLE
Make namespace follow folder structure?

### ISSUE THREAD

**Issue by bacusters** [movetk/movetk#34]
Maybe this is more of a stylistic question: currently, our namespaces are all prefixed by movetk_ and do not map directly to the folders that the associated methods/classes are in. I personally prefer to synchronize the names of the folders of the (includable) header files with the namespaces that the objects reside in. Using this guideline, it is easier to see what you need to include from a fully qualified name, e.g. movetk::core::MakePoint<> would then reside in some file in 'movetk/core' in the header include folder. Is this something we would want to pursue?

**Comment by aniketmitra001** [comment]
@bacusters  indeed this will make  finding the  required classes easier.  Something we also need to consider  is the schematic of the [components](https://github.com/heremaps/movetk/wiki/Overview-of-MoveTK) . The idea was to have a very simple grouping into four namespaces. So, maybe we can reorganise the folder structure so that they are in sync with the namespaces and also change the namespaces from ```movetk_``` to fully qualified names as ```movetk::```

Below is the proposed reorganisation of the folder structure under ```src/include``` . @bacusters  what do you think?
Also adding @mwernerds  to the discussion to get his inputs on the same

![MoveTKFolderStructure](https://user-images.githubusercontent.com/2693003/95979008-45a0bd00-0e1b-11eb-8aac-963831832ca9.png)

**Comment by bacusters** [comment]
I think that is a nice setup yes! One question: do we need the 'algorithms' folder in between? I think the folders for the different components are self-explaining enough to not need that? Or do we have common interfaces that we need in the movetk::algorithms namespace?

**Comment by aniketmitra001** [comment]
> I think that is a nice setup yes! One question: do we need the 'algorithms' folder in between? I think the folders for the different components are self-explaining enough to not need that? Or do we have common interfaces that we need in the movetk::algorithms namespace?

Well that is a design choice we will have to think about , do we want a common traits and interface under ```movetk::algorithms``` or we wish to have traits and interfaces under each component?

One thing is certain that we will now need an interface similar to [DistanceTraits.h](https://github.com/heremaps/movetk/blob/dtw-implementation/src/include/movetk/metric/DistanceTraits.h) & [DistanceInterface.h](https://github.com/heremaps/movetk/blob/dtw-implementation/src/include/movetk/metric/DistanceInterface.h)  for the DTW implementation by @mstroila  because when the DTW algorithm moves to ```movetk/algo/Similarity.h```  this will create the same circular reference problem since 
```Similarity.h``` includes ```GeometryInterface.h```  and  because ```boost.geometry``` already has an implementation of DTW , we  have the following interface in ```GeometryInterface.h``` 

```cpp
      template<class GeometryTraits, class Norm, class T>
    struct dynamic_time_warping_algorithm {
        typedef T dynamic_time_warping;
    };

    template<class GeometryTraits, class Norm>
    struct dynamic_time_warping_algorithm<GeometryTraits, Norm, void> {
        typedef movetk_support::Dynamic_Time_Warping<GeometryTraits, Norm> dynamic_time_warping;
    };

    template<class GeometryTraits, class Norm>
    struct ComputeDynamicTimeWarpingDistance {
        template<class InputIterator,
                typename = movetk_core::requires_random_access_iterator<InputIterator>,
                typename = movetk_core::requires_movetk_point<GeometryTraits,
                        typename InputIterator::value_type>>
        typename GeometryTraits::NT operator()(InputIterator polyline_a_first, InputIterator polyline_a_beyond,
                                               InputIterator polyline_b_first, InputIterator polyline_b_beyond) {
            typedef dynamic_time_warping_algorithm<GeometryTraits, Norm,
                    typename GeometryTraits::MovetkDynamicTimeWarpingDistance> algorithm;
            typename algorithm::dynamic_time_warping distance;
            return distance(polyline_a_first, polyline_a_beyond, polyline_b_first, polyline_b_beyond);
        }

    };
```
 which needs to know the definition of ```movetk_support::Dynamic_Time_Warping```

So, going forward, we will have interfaces for algorithms as  well, whether we wish to have a common traits and interface header (```movetk/algo/AlgorithmTraits.h```  & ```movetk/algo/AlgorithmInterfaces.h``` ) or have a separate (```movetk/algo/similarity/SimilarityTraits.h```  & ```movetk/algo/similarity/SimilarityInterface.h``` )  is something we need to decide upon.
